version: "3.9"

services:
  webhook:
    build: .
    container_name: webhook-listener
    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - /home/pi/nextcloud-data/jesus/files/webhookPayloads:/app/received_webhooks
      - ./replied_users.json:/app/replied_users.json

    ports:
      - "5000:5000"
